config/routes.rb
Rails.application.routes.draw do
  resources :cities, :only => [:index, :show] do
    scope module: :cities do
      resources :weathers, :except => [:index, :show] 
    end
    collection do
      get :update_temps
    end
  end
  root :to => "cities#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    has_many :weathers

    validates :name, presence: true
    accepts_nested_attributes_for :weathers

    before_create :set_opm_id

    def self.update_temps
        #Get and store current temps for all cities
        opm_ids = self.all.collect{|city| city.opm_id}.compact.join(',')
        hash = OpmApi.several_cities_data(opm_ids)
        hash&.each do |opm_id,temp|
            city = City.find_by(opm_id: opm_id)
            weather = Weather.new(temp: temp)
            city.weathers << weather
        end
    end

    def set_opm_id
        #Get id used by opm for current city name
        opm_id = OpmApi.get_opm_id(self.name)
        self.opm_id = opm_id
    end
end

app/models/weather.rb
class Weather < ApplicationRecord
  belongs_to :city
  validates :temp, numericality: { greater_than: -100, less_than: 100 }
 

  paginates_per 5
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cities/weathers_controller.rb
class Cities::WeathersController < ApplicationController
    before_action :set_weather, only: [:show, :edit, :update, :destroy]
    before_action :set_city
  
    # GET /weathers/new
    def new
      @weather = Weather.new
      @button_text = "Crear"
    end
  
    # GET /weathers/1/edit
    def edit
      @button_text = "Actualizar"
    end
  
    # POST /weathers
    # POST /weathers.json
    def create
      @weather = Weather.new(weather_params)
      @weather.city = @city
  
      respond_to do |format|
        if @weather.save
          format.html { redirect_to @city, notice: 'Temperatura añadida correctamente.'}
          format.json { render :show, status: :created, location: @city }
        else
          format.html { render :new }
          format.json { render json: @weather.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /weathers/1
    # PATCH/PUT /weathers/1.json
    def update
      respond_to do |format|
        if @weather.update(weather_params)
          format.html { redirect_to @city, notice: 'Temperatura actualizada correctamente.' }
          format.json { render :show, status: :ok, location: @city }
        else
          format.html { render :edit }
          format.json { render json: @weather.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /weathers/1
    # DELETE /weathers/1.json
    def destroy
      @weather.destroy
      respond_to do |format|
        format.html { redirect_to @city, notice: 'Temperatura eliminada correctamente.' }
        format.json { head :no_content }
      end
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_weather
        @weather = Weather.find(params[:id])
      end

      def set_city
        @city = City.find(params[:city_id])
      end
  
      # Never trust parameters from the scary internet, only allow the white list through.
      def weather_params
        params.require(:weather).permit(:temp)
      end
  end
  

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities
  # GET /cities.json
  def index
    @cities = City.includes(:weathers)
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
    @weathers = @city.weathers.order(created_at: :desc).page params[:page]
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def update_temps
    City.update_temps
    respond_to do |format|
      format.html {redirect_to cities_url, notice: 'Temperaturas Actualizadas'}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:name, :opm_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/weathers_helper.rb
module WeathersHelper
end

app/views/cities/_form.html.erb
<%= form_with(model: city, local: true) do |form| %>
  <% if city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% city.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<h1>Editing City</h1>

<%= render 'form', city: @city %>

<%= link_to 'Show', @city %> |
<%= link_to 'Back', cities_path %>

app/views/cities/index.html.erb
<%= link_to update_temps_cities_path, class: "btn btn-dark" do %>
              <%= fa_icon "repeat"%> Actualizar temperaturas
<% end %>
<div class="table-responsive mt-4">
  <table class="table">
  <thead>
    <tr>
      <th scope="col" class="text-center">Ciudad</th>
      <th scope="col" class="text-center">Temperatura (°C) </th>
      <th scope="col" class="text-center">Acciones</th>
    </tr>
  </thead>
  <tbody>
    <% @cities.each do |city| %>
      <tr>
        <td class="text-center"><%= city.name %></td>
        <td class="text-center"><%= city.weathers.last&.temp || "No hay datos" %></td>
        <td class="text-center"><%= link_to city, class: "btn btn-info" do %>
              <%= fa_icon "eye"%> Ver más
            <% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<%# link_to 'New City', new_city_path %>

app/views/cities/new.html.erb
<h1>New City</h1>

<%= render 'form', city: @city %>

<%= link_to 'Back', cities_path %>

app/views/cities/show.html.erb
<p>
  <strong>Ciudad:</strong>
  <%= @city.name %>
</p>

<div class="table-responsive">
  <table class="table">
  <thead>
    <tr>
      <th scope="col" class="text-center">Temperatura (°C)</th>
      <th scope="col" class="text-center">Fecha de consulta</th>
      <th scole="col" class="text-center"></th>
    </tr>
  </thead>

  <tbody>
    <% @weathers.each do |weather| %>
      <tr>
        <td class="text-center"><%= weather.temp %></td>
        <td class="text-center"><%= weather.created_at.strftime("%d/%m/%y %H:%M:%S") %></td>
        <td class="text-center"><%= link_to edit_city_weather_path(@city,weather), class: "btn btn-warning" do %>
              <%= fa_icon "pencil"%>
            <% end%>
            <%= link_to [@city,weather], method: :delete, class: "btn btn-danger", data: { confirm: '¿Seguro?' } do %>
              <%= fa_icon "times"%>
            <% end%> </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<%= paginate @weathers, pagination_class: "pagination-sm" %>


<%= link_to cities_path, class: "btn btn-info" do %>
    <%= fa_icon "arrow-left"%> Volver
<% end %>


<%= link_to new_city_weather_path(@city), class: "btn btn-success" do %>
    <%= fa_icon "plus"%> Añadir temperatura
<% end %>

app/views/cities/weathers/_form.html.erb
<%= simple_form_for([@city,@weather]) do |f| %>

  <div class="form-group mb-2">
    <%= f.input :temp, label: false %>
  </div>
  
  <div class="form-group mb-2">
    <%= f.button :button, class: "btn btn-outline-success" do %>
      <%= fa_icon "check" %>
    <% end %>
  </div>
  
  
<% end %>

app/views/cities/weathers/edit.html.erb
<h2><%= @city.name%></h2>
<h1>Editar Temperatura</h1>

<%= render 'form', weather: @weather %>

<%# link_to 'Show', @weather %>
<%= link_to city_path(@city), class: "btn btn-info" do %>
    <%= fa_icon "arrow-left"%> Volver
<% end %>

app/views/cities/weathers/new.html.erb
<h2><%= @city.name%></h2>
<h1>Añadir Temperatura</h1>

<%= render 'form', weather: @weather %>

<%= link_to city_path(@city), class: "btn btn-info" do %>
    <%= fa_icon "arrow-left"%> Volver
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeatherApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/"><i class="fa fa-home"></i> Inicio<span class="sr-only">(current)</span></a>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container mt-2">
      <% if notice %>
        <div class="alert alert-success alert-dismissible fade show" role="alert">
          <%= notice %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end%>
      <%= yield %>
    </div>
  </body>
   
</html>

app/views/weathers/_form.html.erb
<%= form_with(model: weather, local: true) do |form| %>
  <% if weather.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(weather.errors.count, "error") %> prohibited this weather from being saved:</h2>

      <ul>
      <% weather.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :temp %>
    <%= form.text_field :temp %>
  </div>

  <div class="field">
    <%= form.label :city_id %>
    <%= form.text_field :city_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>